name: Generate Site Artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm setup
        run: |
          npm install
          npm run build
      - name: Site artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: out